version: "3.5"

services:

  gitproxy:
    container_name: gitproxy
    image: vectra/gitproxy:latest
    restart: always
    build:
      context: .
    environment:
     - GIT_HOST=bitbucket.org
     - GIT_PORT=443
     - GIT_USER=myuser
     - GIT_PASSWORD=mypassword
     - AUTH_KEY=secret
    ports:
    - "3000:3000"
